name: Cancel Previous Runs
on:
  workflow_run:
    workflows: ["macOS CI", "Linux CI", "Windows CI"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}